about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - ESP
  summary: ESP variants
build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch37-esp-variants
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - perl
  - vt
  - zlib
  run:
  - gsort
  - htslib
  - perl
  - vt
  - zlib
source:
  path: .
