os:
- linux
sudo: required
dist: trusty
language: c
install: travis_wait 119 scripts/travis-setup.sh
script: travis_wait 500 scripts/travis-test.sh
ANACONDA_GGD_TOKEN=:
  secure: WcElPRbO0pTtrkYobhpEfNXFQ8oBw5TCCFEqLugUvUfanQWft0d9gM1he8rZYz9iDQ88GqttzyzPC/YAWWQ/M/rKb+Exv0MSRgrUZcNil7rEsL3/ULiAECg26AQ7NRtjEIBkmRX0bOg43ooEaxqXsK50u4z5BO/y4KCgvvBaqE2yOj2u4xOq29cxSn15clGRihbMASfx1ALzZlxw/AZt87omFk8rqN0TQCWsuGfAoPyfW/6mco7lv4qKwE2jQD8E0qY/gWgpQ5WoZWrVkn36CY7O3It+uOFGxJGKIxTQi3LRVbrP5+RFf4hd8cSTKgj7225sTBLDLNT8R9jm7kQSlmCIIWeFdCihX1g00x9u1wNhbK2R3w4BpE1j5n40TeK6xTjgvonHTNjMSNRHf7fzzhsqrei7wqYgmWVEpM6Ht5IT6pA+aL725yqRBIQaO2k/iZg2EIo2lxXLWY49qYqjs+CI+hxFIA8rtv3pkdjhhNhnEE5Rn65KpEqK+OSCAzGcgvJsEhnLxZcXNHVna5/Ju4SqtTnP3jvXylDAuji8RbYRyWS0B0PTgUdau6rXLITa6RzjZ3GXV8OoVjrQzv3G51HXvQoXbweXDe5kxc6pWHOykN1eHSDOHv10hYTLuxTvc9yfdhWF+7m8lrbwnc4yPeHMDw5Kr96v7MC6/K4pU1E=
