about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - rmsk
  - region
  summary: RepeatMasker track from UCSC
build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: hg38-repeatmasker
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
